export const identityRegistryAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_enrollmentVerifier", type: "address", internalType: "address" },
      { name: "_revocationVerifier", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addTrustedIssuer",
    inputs: [
      { name: "pubKeyX", type: "uint256", internalType: "uint256" },
      { name: "pubKeyY", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "enroll",
    inputs: [
      { name: "_pA", type: "uint256[2]", internalType: "uint256[2]" },
      { name: "_pB", type: "uint256[2][2]", internalType: "uint256[2][2]" },
      { name: "_pC", type: "uint256[2]", internalType: "uint256[2]" },
      { name: "_pubSignals", type: "uint256[8]", internalType: "uint256[8]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeIdentityWithProof",
    inputs: [
      { name: "_pA", type: "uint256[2]", internalType: "uint256[2]" },
      { name: "_pB", type: "uint256[2][2]", internalType: "uint256[2][2]" },
      { name: "_pC", type: "uint256[2]", internalType: "uint256[2]" },
      { name: "_pubSignals", type: "uint256[4]", internalType: "uint256[4]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getIdentity",
    inputs: [{ name: "hashID", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "record",
        type: "tuple",
        internalType: "struct IdentityRegistry.IdentityRecord",
        components: [
          { name: "validUntil", type: "uint256", internalType: "uint256" },
          { name: "issuerPubKeyX", type: "uint256", internalType: "uint256" },
          { name: "issuerPubKeyY", type: "uint256", internalType: "uint256" },
          { name: "holderPubKeyX", type: "uint256", internalType: "uint256" },
          { name: "holderPubKeyY", type: "uint256", internalType: "uint256" },
          { name: "exists", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getIdentityCount",
    inputs: [],
    outputs: [{ name: "count", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getVerificationKey",
    inputs: [{ name: "hashID", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "vkX", type: "uint256", internalType: "uint256" },
      { name: "vkY", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "identities",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "validUntil", type: "uint256", internalType: "uint256" },
      { name: "issuerPubKeyX", type: "uint256", internalType: "uint256" },
      { name: "issuerPubKeyY", type: "uint256", internalType: "uint256" },
      { name: "holderPubKeyX", type: "uint256", internalType: "uint256" },
      { name: "holderPubKeyY", type: "uint256", internalType: "uint256" },
      { name: "exists", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isIdentityValid",
    inputs: [{ name: "hashID", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "isValid", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isIssuerTrusted",
    inputs: [
      { name: "pubKeyX", type: "uint256", internalType: "uint256" },
      { name: "pubKeyY", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "isTrusted", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_REVOKE_BLOCK_AGE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "enrollmentVerifier",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "revocationVerifier",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "IdentityEnrolled",
    inputs: [
      { name: "hashID", type: "uint256", indexed: true, internalType: "uint256" },
      {
        name: "issuerPubKeyHash",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "validUntil", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "IdentityRevoked",
    inputs: [
      { name: "hashID", type: "uint256", indexed: true, internalType: "uint256" },
      {
        name: "challengeBlock",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "IdentityAlreadyExists", inputs: [] },
  { type: "error", name: "IdentityNotFound", inputs: [] },
  { type: "error", name: "InvalidProof", inputs: [] },
  { type: "error", name: "IssuerNotTrusted", inputs: [] },
  { type: "error", name: "NotOwner", inputs: [] },
  { type: "error", name: "ChallengeBlockInFuture", inputs: [] },
  { type: "error", name: "StaleChallenge", inputs: [] },
  { type: "error", name: "RevocationKeyMismatch", inputs: [] },
] as const;
