export const identityRegistryAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_enrollmentVerifier", type: "address", internalType: "address" },
      { name: "_oprfPkX", type: "uint256", internalType: "uint256" },
      { name: "_oprfPkY", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTrustedOprfPublicKey",
    inputs: [
      { name: "pkX", type: "uint256", internalType: "uint256" },
      { name: "pkY", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addTrustedIssuer",
    inputs: [
      { name: "pubKeyX", type: "uint256", internalType: "uint256" },
      { name: "pubKeyY", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeTrustedIssuer",
    inputs: [
      { name: "pubKeyX", type: "uint256", internalType: "uint256" },
      { name: "pubKeyY", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "enroll",
    inputs: [
      { name: "proof", type: "bytes", internalType: "bytes" },
      { name: "publicSignals", type: "bytes32[]", internalType: "bytes32[]" },
      { name: "walletAddress", type: "address", internalType: "address" },
      { name: "enrollmentSignature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revoke",
    inputs: [
      { name: "nullifier", type: "uint256", internalType: "uint256" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getIdentity",
    inputs: [{ name: "nullifier", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "record",
        type: "tuple",
        internalType: "struct IdentityRegistry.IdentityRecord",
        components: [
          { name: "validUntil", type: "uint256", internalType: "uint256" },
          { name: "issuerPubKeyX", type: "uint256", internalType: "uint256" },
          { name: "issuerPubKeyY", type: "uint256", internalType: "uint256" },
          { name: "walletAddress", type: "address", internalType: "address" },
          { name: "exists", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getIdentityCount",
    inputs: [],
    outputs: [{ name: "count", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isIdentityValid",
    inputs: [{ name: "nullifier", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "isValid", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isIssuerTrusted",
    inputs: [
      { name: "pubKeyX", type: "uint256", internalType: "uint256" },
      { name: "pubKeyY", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "isTrusted", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "domainSeparator",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hashEnrollmentAuthorization",
    inputs: [
      { name: "proof", type: "bytes", internalType: "bytes" },
      { name: "publicSignals", type: "bytes32[]", internalType: "bytes32[]" },
      { name: "walletAddress", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hashRevocationAuthorization",
    inputs: [
      { name: "nullifier", type: "uint256", internalType: "uint256" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "enrollmentVerifier",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owners",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "trustedOprfPkX",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "trustedOprfPkY",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "IdentityEnrolled",
    inputs: [
      { name: "nullifier", type: "uint256", indexed: true, internalType: "uint256" },
      {
        name: "issuerPubKeyHash",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "validUntil", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "walletAddress", type: "address", indexed: true, internalType: "address" },
      { name: "oprfPkX", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "oprfPkY", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "IdentityRevoked",
    inputs: [
      { name: "nullifier", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "walletAddress", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TrustedOprfPublicKeyUpdated",
    inputs: [
      { name: "oldPkX", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "oldPkY", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "newPkX", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "newPkY", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "IssuerAdded",
    inputs: [
      {
        name: "issuerPubKeyHash",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "IssuerRemoved",
    inputs: [
      {
        name: "issuerPubKeyHash",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "IdentityAlreadyExists", inputs: [] },
  { type: "error", name: "IdentityNotFound", inputs: [] },
  { type: "error", name: "IdentityExpired", inputs: [] },
  { type: "error", name: "InvalidFieldElement", inputs: [] },
  { type: "error", name: "InvalidOprfMetadata", inputs: [] },
  { type: "error", name: "InvalidProof", inputs: [] },
  { type: "error", name: "InvalidPublicSignalLength", inputs: [] },
  { type: "error", name: "InvalidWalletAddress", inputs: [] },
  { type: "error", name: "InvalidEnrollmentAuthorization", inputs: [] },
  { type: "error", name: "InvalidRevocationSignature", inputs: [] },
  { type: "error", name: "RevocationSignatureExpired", inputs: [] },
  { type: "error", name: "InvalidSignature", inputs: [] },
  { type: "error", name: "InvalidNullifier", inputs: [] },
  { type: "error", name: "InvalidIssuerPublicKey", inputs: [] },
  { type: "error", name: "IssuerNotTrusted", inputs: [] },
  { type: "error", name: "NotOwner", inputs: [] },
  { type: "error", name: "UntrustedOprfPublicKey", inputs: [] },
] as const;
